package building

// Auto-generated by gen_block_colors.py from blocks.zip textures
// Total blocks: 775
// BlockTextureColor returns the approximate texture-derived color for a block name.
// The color is computed as the average of all non-special face textures for that block.
func blockTextureColor(blockName string) (string, bool) {
	if c, ok := textureColorMap[blockName]; ok {
		return c, true
	}
	return "", false
}

var textureColorMap = map[string]string{
	"acacia_door": "#76422a",
	"acacia_leaves": "#838282",
	"acacia_log": "#7e5c46",
	"acacia_planks": "#a85a32",
	"acacia_sapling": "#33330a",
	"acacia_trapdoor": "#774227",
	"activator_rail": "#4e352d",
	"allium": "#23222c",
	"amethyst_block": "#8561bf",
	"amethyst_cluster": "#594571",
	"ancient_debris": "#5e4038",
	"andesite": "#888888",
	"angler_pottery_pattern": "#6e3f32",
	"anvil": "#323232",
	"archer_pottery_pattern": "#6c3e31",
	"arms_up_pottery_pattern": "#6d3f32",
	"azalea": "#4a5b23",
	"azalea_leaves": "#4b6026",
	"azalea_leaves_flowers": "#4f5830",
	"azure_bluet": "#273026",
	"bamboo_block": "#858e3b",
	"bamboo_door": "#b19e4b",
	"bamboo_fence": "#8a7c3b",
	"bamboo_fence_gate": "#524a22",
	"bamboo_leaf": "#7cc72b",
	"bamboo_mosaic": "#beaa4e",
	"bamboo_planks": "#c1ad50",
	"bamboo_sapling": "#d6d7c9",
	"bamboo_singleleaf": "#f0f4ea",
	"bamboo_small_leaf": "#94bf67",
	"bamboo_stem": "#5d9013",
	"bamboo_trapdoor": "#a49446",
	"barrel": "#765834",
	"barrel_top_open": "#5c4322",
	"barrier": "#610000",
	"basalt": "#4c4c51",
	"beacon": "#75dcd7",
	"bed_feet": "#611410",
	"bed_feet_end": "#39160c",
	"bed_head": "#764e4b",
	"bed_head_end": "#4e473e",
	"bedrock": "#555555",
	"bee_nest": "#bb914d",
	"beehive": "#a4834d",
	"beetroots": "#121b08",
	"bell": "#f8e98a",
	"big_dripleaf": "#65802e",
	"big_dripleaf_side1": "#000100",
	"big_dripleaf_side2": "#0f1307",
	"big_dripleaf_stem": "#1d250f",
	"birch_door": "#d6c9a0",
	"birch_leaves": "#797779",
	"birch_log": "#ccc5ac",
	"birch_planks": "#c0af79",
	"birch_sapling": "#303d1e",
	"birch_trapdoor": "#cfc29d",
	"black_candle": "#797879",
	"black_concrete": "#080a0f",
	"black_concrete_powder": "#191a1f",
	"black_glass": "#191919",
	"black_glass_pane": "#181818",
	"black_glazed_terracotta": "#431e20",
	"black_shulker_box": "#19191d",
	"black_terracotta": "#251610",
	"black_wool": "#141519",
	"blackstone": "#2a2328",
	"blade_pottery_pattern": "#714133",
	"blast_furnace": "#666564",
	"blue_candle": "#797b82",
	"blue_concrete": "#2c2e8f",
	"blue_concrete_powder": "#4649a6",
	"blue_coral_block": "#3157ce",
	"blue_glass": "#334cb2",
	"blue_glass_pane": "#3049ab",
	"blue_glazed_terracotta": "#2f408b",
	"blue_ice": "#74a7fd",
	"blue_orchid": "#071515",
	"blue_shulker_box": "#2b2d8c",
	"blue_terracotta": "#4a3b5b",
	"blue_wool": "#35399d",
	"bone_block": "#dbd7c1",
	"bookshelf": "#755e3b",
	"border": "#b5392f",
	"brewer_pottery_pattern": "#6e3f32",
	"brewing_stand": "#584e49",
	"brick": "#966153",
	"brown_candle": "#7f7b78",
	"brown_concrete": "#603b1f",
	"brown_concrete_powder": "#7d5435",
	"brown_glass": "#664c33",
	"brown_glass_pane": "#614930",
	"brown_glazed_terracotta": "#776a55",
	"brown_mushroom_block": "#956f51",
	"brown_shulker_box": "#6a4223",
	"brown_terracotta": "#4d3323",
	"brown_wool": "#724728",
	"budding_amethyst": "#8460ba",
	"burn_pottery_pattern": "#6f4032",
	"cactus": "#4b2b30",
	"cake": "#6d5042",
	"calcite": "#dfe0dc",
	"calibrated_sculk_sensor": "#1b4f64",
	"calibrated_sculk_sensor_amethyst": "#312838",
	"calibrated_sculk_sensor_input": "#1d2232",
	"camera": "#534229",
	"campfire": "#5d4b2d",
	"candle": "#878581",
	"carpet": "#826e67",
	"carrots": "#13210a",
	"cartography_table": "#675743",
	"cartography_table_side1": "#463222",
	"cartography_table_side2": "#513d2a",
	"cartography_table_side3": "#432b14",
	"cauldron": "#2d2c2e",
	"cauldron_water": "#cdcdcd",
	"cave_vines_body": "#393e17",
	"cave_vines_head": "#373f17",
	"chain1": "#050608",
	"chain2": "#050607",
	"chain_command_block": "#83a193",
	"chain_command_block_conditional": "#81a193",
	"cherry_door": "#cfa09a",
	"cherry_leaves": "#d199af",
	"cherry_log": "#77575a",
	"cherry_planks": "#e2b2ac",
	"cherry_sapling": "#4e3844",
	"cherry_trapdoor": "#c29994",
	"chest": "#7d5b26",
	"chiseled_bookshelf": "#927557",
	"chiseled_bookshelf_empty": "#5a4629",
	"chiseled_bookshelf_occupied": "#795e45",
	"chiseled_copper": "#b86449",
	"chiseled_deepslate": "#363636",
	"chiseled_nether_bricks": "#2d161b",
	"chiseled_polished_blackstone": "#353038",
	"chiseled_quartz_block": "#e7e2d9",
	"chiseled_red_sandstone": "#b7601b",
	"chiseled_resin_bricks": "#c85418",
	"chiseled_sandstone": "#d8ca9b",
	"chiseled_stone_bricks": "#777677",
	"chiseled_tuff": "#5b6058",
	"chiseled_tuff_bricks": "#686c64",
	"chorus_flower": "#977897",
	"chorus_flower_dead": "#603d5e",
	"chorus_plant": "#5d395d",
	"clay": "#a0a6b3",
	"coal_block": "#100f0f",
	"coal_ore": "#696969",
	"coarse_dirt": "#77553b",
	"cobbled_deepslate": "#4d4d50",
	"cobblestone": "#7f7f7f",
	"cocoa": "#332411",
	"command_block": "#b1866b",
	"comparator": "#aaa09e",
	"composter": "#6c4621",
	"concrete": "#725c5b",
	"concretePowder": "#877870",
	"conduit_base": "#a58c71",
	"conduit_cage": "#bca994",
	"conduit_closed": "#125770",
	"conduit_open": "#24657c",
	"conduit_wind_horizontal": "#fefefe",
	"conduit_wind_vertical": "#fefefe",
	"copper_bars": "#462419",
	"copper_block": "#c06b4f",
	"copper_bulb": "#b97551",
	"copper_chain1": "#110906",
	"copper_chain2": "#0f0805",
	"copper_chest_inventory": "#bc694d",
	"copper_door": "#a85f48",
	"copper_grate": "#864b37",
	"copper_lantern": "#412c1f",
	"copper_ore": "#7c7d78",
	"copper_torch": "#090805",
	"copper_trapdoor": "#97543f",
	"coral": "#a35883",
	"coral_block": "#92697d",
	"cornflower": "#e7ecf0",
	"cracked_deepslate_bricks": "#404041",
	"cracked_deepslate_tiles": "#343434",
	"cracked_nether_bricks": "#281417",
	"cracked_polished_blackstone_bricks": "#2c252b",
	"cracked_stone_bricks": "#767576",
	"crafter": "#6e5d5e",
	"crafter_east": "#7f725d",
	"crafter_north": "#6c655b",
	"crafter_south": "#7c7060",
	"crafter_west": "#81735e",
	"crafting_table": "#7d5d3a",
	"creaking_heart": "#6e4632",
	"crimson_door": "#72364f",
	"crimson_fungus": "#210a06",
	"crimson_log": "#662531",
	"crimson_nylium": "#761c1c",
	"crimson_planks": "#653046",
	"crimson_roots": "#25020c",
	"crimson_trapdoor": "#572a3d",
	"crying_obsidian": "#200a3c",
	"cut_copper": "#bf6a50",
	"cyan_candle": "#77807f",
	"cyan_concrete": "#157788",
	"cyan_concrete_powder": "#24939d",
	"cyan_glass": "#4c7f99",
	"cyan_glass_pane": "#497a93",
	"cyan_glazed_terracotta": "#34767d",
	"cyan_shulker_box": "#147987",
	"cyan_terracotta": "#565b5b",
	"cyan_wool": "#158991",
	"dandelion": "#121505",
	"danger_pottery_pattern": "#6f4032",
	"dark_oak_door": "#4a3218",
	"dark_oak_leaves": "#8a898a",
	"dark_oak_log": "#3f2d18",
	"dark_oak_planks": "#422b14",
	"dark_oak_sapling": "#1a260d",
	"dark_oak_trapdoor": "#4b3117",
	"dark_prismarine": "#335b4b",
	"daylight_detector": "#625540",
	"daylight_detector_inverted": "#6a6d70",
	"dead_blue_coral_block": "#827b77",
	"dead_bush": "#2d2923",
	"dead_pink_coral_block": "#7c7572",
	"dead_purple_coral_block": "#837b77",
	"dead_red_coral_block": "#837b77",
	"dead_yellow_coral_block": "#857e7a",
	"decorated_pot": "#713f33",
	"decorated_pot_base": "#573027",
	"deepslate": "#535355",
	"deepslate_bricks": "#464647",
	"deepslate_coal_ore": "#4a4a4c",
	"deepslate_copper_ore": "#5c5d59",
	"deepslate_diamond_ore": "#536a6a",
	"deepslate_emerald_ore": "#4e6857",
	"deepslate_gold_ore": "#73664e",
	"deepslate_iron_ore": "#6a635e",
	"deepslate_lapis_ore": "#4f5a73",
	"deepslate_redstone_ore": "#68494a",
	"deepslate_tiles": "#363637",
	"detector_rail": "#4e3e36",
	"diamond_block": "#62ede4",
	"diamond_ore": "#798d8c",
	"diorite": "#bcbcbc",
	"dirt": "#866043",
	"dirt_path": "#8a6b3f",
	"dispenser": "#7a7979",
	"dispenser_front_vertical": "#626161",
	"double_stone_slab": "#918a82",
	"dragon_egg": "#0c090f",
	"dried_ghast_state": "#464444",
	"dried_ghast_state_1_left": "#3c3737",
	"dried_ghast_state_1_right": "#3c3737",
	"dried_ghast_state_1_tentacles": "#777474",
	"dried_ghast_state_2_left": "#444141",
	"dried_ghast_state_2_right": "#444141",
	"dried_ghast_state_2_tentacles": "#918e8e",
	"dried_ghast_state_3_left": "#4d4a4a",
	"dried_ghast_state_3_right": "#4d4a4a",
	"dried_ghast_state_3_tentacles": "#aba8a8",
	"dried_ghast_state_4_left": "#5d5d5d",
	"dried_ghast_state_4_right": "#5d5d5d",
	"dried_ghast_state_4_tentacles": "#dfdddd",
	"dried_kelp": "#323a26",
	"dried_kelp_side_a": "#26301d",
	"dried_kelp_side_b": "#26301d",
	"dripstone_block": "#866b5c",
	"dropper": "#7a7979",
	"dropper_front_vertical": "#616060",
	"emerald_block": "#2acb57",
	"emerald_ore": "#6c8873",
	"enchanting_table": "#3c2732",
	"end_portal": "#000000",
	"end_rod": "#2f2c2a",
	"end_stone": "#dbde9e",
	"end_stone_bricks": "#dae0a2",
	"ender_chest": "#1d2c2d",
	"endframe": "#6a7e62",
	"endframe_eye": "#0d1a17",
	"explorer_pottery_pattern": "#693d30",
	"exposed_chiseled_copper": "#9a7764",
	"exposed_copper": "#a17d67",
	"exposed_copper_bars": "#3c3028",
	"exposed_copper_bulb": "#a57d5e",
	"exposed_copper_chain1": "#0e0b09",
	"exposed_copper_chain2": "#0d0a08",
	"exposed_copper_chest_inventory": "#a17967",
	"exposed_copper_door": "#8e6d5d",
	"exposed_copper_grate": "#715849",
	"exposed_copper_lantern": "#3d362b",
	"exposed_copper_trapdoor": "#806353",
	"exposed_cut_copper": "#9a7965",
	"exposed_lightning_rod": "#d8d2cf",
	"eyeblossom": "#161414",
	"eyeblossom_blooming": "#1f1c1b",
	"eyeblossom_eyes_blooming": "#030200",
	"eyeblossom_stem_blooming": "#1c1a1a",
	"farmland": "#70492a",
	"fence": "#9c8152",
	"fence_gate": "#9c8152",
	"fire": "#f08020",
	"firefly_bush": "#1b1a0d",
	"fletcher_table": "#c5b485",
	"fletcher_table_side1": "#bfa781",
	"fletcher_table_side2": "#ad9b6f",
	"flow_pottery_pattern": "#6c3e31",
	"flower": "#454b43",
	"flowering_azalea": "#595e36",
	"flowering_azalea_leaves": "#5b6838",
	"flowing_lava": "#d04010",
	"flowing_water": "#3050a0",
	"friend_pottery_pattern": "#6d3f31",
	"frogspawn": "#221e1b",
	"frosted_ice": "#8ab3fc",
	"furnace": "#6e6c67",
	"gilded_blackstone": "#372a26",
	"glass": "#8c9597",
	"glass_pane": "#aad2d9",
	"glow_item_frame": "#946740",
	"glow_lichen": "#2e3531",
	"glowing_obsidian": "#50020c",
	"glowstone": "#ab8354",
	"gold_block": "#f6d03d",
	"gold_ore": "#91856a",
	"granite": "#956755",
	"grass": "#727272",
	"grass_block": "#a99685",
	"gravel": "#837f7e",
	"gray_candle": "#7c7d7d",
	"gray_concrete": "#36393d",
	"gray_concrete_powder": "#4c5154",
	"gray_glass": "#4c4c4c",
	"gray_glass_pane": "#494949",
	"gray_glazed_terracotta": "#535a5d",
	"gray_shulker_box": "#373a3e",
	"gray_terracotta": "#392a23",
	"gray_wool": "#3e4447",
	"green_candle": "#7c7d76",
	"green_concrete": "#495b24",
	"green_concrete_powder": "#61772c",
	"green_glass": "#667f33",
	"green_glass_pane": "#617a30",
	"green_glazed_terracotta": "#758e43",
	"green_shulker_box": "#4f641f",
	"green_terracotta": "#4c532a",
	"green_wool": "#546d1b",
	"guster_pottery_pattern": "#6f4032",
	"hanging_roots": "#2f211a",
	"hay_block": "#a58919",
	"heart_pottery_pattern": "#6b3d30",
	"heartbreak_pottery_pattern": "#6c3e31",
	"heavy_core": "#3d4046",
	"honey_block": "#f7ad2a",
	"honeycomb": "#e5941d",
	"hopper": "#353537",
	"howl_pottery_pattern": "#6d3f32",
	"ice": "#91b7fd",
	"iron_bars": "#3e3f3d",
	"iron_block": "#dcdcdc",
	"iron_door": "#b0afaf",
	"iron_ore": "#88817a",
	"iron_trapdoor": "#aeadad",
	"itemframe_background": "#74432a",
	"jack_o_lantern": "#d48020",
	"jigsaw": "#3a313c",
	"jigsaw_lock": "#2d262f",
	"jukebox": "#5a3d2b",
	"jungle_door": "#976d4c",
	"jungle_leaves": "#8e8c85",
	"jungle_log": "#75582f",
	"jungle_planks": "#a07350",
	"jungle_sapling": "#0f1b05",
	"jungle_trapdoor": "#7f5c40",
	"ladder": "#46361e",
	"lantern": "#2b2522",
	"lapis_block": "#1e438c",
	"lapis_ore": "#6b758d",
	"large_amethyst_bud": "#31263d",
	"lava": "#d04010",
	"leaf_litter": "#4e4e4e",
	"leaves": "#7c7a7a",
	"leaves2": "#868586",
	"lectern": "#9a7746",
	"lectern_sides": "#957543",
	"lever": "#080705",
	"light_blue_candle": "#788185",
	"light_blue_concrete": "#2389c6",
	"light_blue_concrete_powder": "#4ab4d5",
	"light_blue_glass": "#6699d8",
	"light_blue_glass_pane": "#6193d0",
	"light_blue_glazed_terracotta": "#5ea4d0",
	"light_blue_shulker_box": "#31a3d4",
	"light_blue_terracotta": "#716c89",
	"light_blue_wool": "#3aafd9",
	"light_gray_candle": "#7f7f7e",
	"lightning_rod": "#221c19",
	"lily_of_the_valley": "#dfebd8",
	"lime_candle": "#7e8376",
	"lime_concrete": "#5ea818",
	"lime_concrete_powder": "#7dbd29",
	"lime_glass": "#7fcc19",
	"lime_glass_pane": "#7ac418",
	"lime_glazed_terracotta": "#a2c537",
	"lime_shulker_box": "#63ac17",
	"lime_terracotta": "#677534",
	"lime_wool": "#70b919",
	"lodestone": "#858689",
	"log": "#856f4d",
	"log2": "#5e442f",
	"loom": "#7f6346",
	"magenta_candle": "#827981",
	"magenta_concrete": "#a9309f",
	"magenta_concrete_powder": "#c053b8",
	"magenta_glass": "#b24cd8",
	"magenta_glass_pane": "#ab49d0",
	"magenta_glazed_terracotta": "#d064bf",
	"magenta_shulker_box": "#ad36a3",
	"magenta_terracotta": "#95586c",
	"magenta_wool": "#bd44b3",
	"magma": "#bc5020",
	"magma_block": "#8e3f1f",
	"mangrove_door": "#702f2e",
	"mangrove_leaves": "#787777",
	"mangrove_log": "#5c3929",
	"mangrove_planks": "#753630",
	"mangrove_propagule": "#0c160a",
	"mangrove_propagule_hanging": "#161c0e",
	"mangrove_roots": "#2e2417",
	"mangrove_trapdoor": "#612825",
	"medium_amethyst_bud": "#1f1828",
	"melon": "#70911e",
	"melon_stem_connected": "#121212",
	"melon_stem_disconnected": "#151515",
	"miner_pottery_pattern": "#6f4032",
	"moss_block": "#596d2d",
	"mossy_cobblestone": "#6e765e",
	"mossy_stone_bricks": "#737969",
	"mourner_pottery_pattern": "#6d3e31",
	"mud": "#3c393c",
	"mud_bricks": "#89674f",
	"muddy_mangrove_roots": "#453a2e",
	"mushroom_block": "#c9aa78",
	"mushroom_brown": "#140f0c",
	"mushroom_red": "#1b0908",
	"mushroom_stem": "#cbc4b9",
	"mycelium": "#705c56",
	"nether_brick": "#2c151a",
	"nether_gold_ore": "#73362a",
	"nether_portal": "#6030a0",
	"nether_quartz_ore": "#75413e",
	"nether_sprouts": "#021210",
	"nether_wart": "#2f0707",
	"nether_wart_block": "#720302",
	"netherite_block": "#423d3f",
	"netherrack": "#612626",
	"note_block": "#583a28",
	"oak_leaves": "#838183",
	"oak_log": "#82673d",
	"oak_planks": "#a2824e",
	"oak_sapling": "#212e11",
	"oak_trapdoor": "#6b5530",
	"observer": "#535151",
	"obsidian": "#0f0a18",
	"ochre_froglight": "#f7efc1",
	"orange_candle": "#877e76",
	"orange_concrete": "#e06100",
	"orange_concrete_powder": "#e3831f",
	"orange_glass": "#d87f33",
	"orange_glass_pane": "#d07a30",
	"orange_glazed_terracotta": "#9a935b",
	"orange_shulker_box": "#ea6a08",
	"orange_terracotta": "#a15325",
	"orange_tulip": "#1a2210",
	"orange_wool": "#f07613",
	"oxeye_daisy": "#303e26",
	"oxidized_chiseled_copper": "#53a184",
	"oxidized_copper": "#52a284",
	"oxidized_copper_bars": "#1d372d",
	"oxidized_copper_bulb": "#678e69",
	"oxidized_copper_chain1": "#070d0b",
	"oxidized_copper_chain2": "#060c0a",
	"oxidized_copper_chest_inventory": "#509e84",
	"oxidized_copper_door": "#488d75",
	"oxidized_copper_grate": "#39705b",
	"oxidized_copper_lantern": "#20392d",
	"oxidized_copper_trapdoor": "#428069",
	"oxidized_cut_copper": "#4f997e",
	"oxidized_lightning_rod": "#0c1813",
	"packed_ice": "#8db4fa",
	"packed_mud": "#8e6a4f",
	"pale_hanging_moss": "#2f312e",
	"pale_hanging_moss_tip": "#212220",
	"pale_moss": "#6a7068",
	"pale_moss_block": "#6a7068",
	"pale_moss_carpet_side_base": "#353835",
	"pale_moss_carpet_side_tip": "#151715",
	"pale_oak_door": "#cfc7c5",
	"pale_oak_leaves": "#6a6f68",
	"pale_oak_log": "#8e8583",
	"pale_oak_planks": "#e3d9d8",
	"pale_oak_sapling": "#2c2a28",
	"pale_oak_trapdoor": "#e5dcda",
	"pearlescent_froglight": "#f0e8e9",
	"peony": "#36393d",
	"pink_candle": "#867e80",
	"pink_concrete": "#d5658e",
	"pink_concrete_powder": "#e499b5",
	"pink_coral_block": "#cf5b9f",
	"pink_glass": "#f27fa5",
	"pink_glass_pane": "#e97a9f",
	"pink_glazed_terracotta": "#eb9ab5",
	"pink_petals": "#634857",
	"pink_petals_stem": "#010101",
	"pink_shulker_box": "#e6799d",
	"pink_terracotta": "#a14e4e",
	"pink_tulip": "#162011",
	"pink_wool": "#ed8dac",
	"piston": "#726a5e",
	"pitcher_crop": "#2b2a20",
	"planks": "#8c6c4e",
	"plenty_pottery_pattern": "#683c2f",
	"podzol": "#6a4b28",
	"pointed_dripstone": "#1c1613",
	"pointed_dripstone_down_base": "#745c50",
	"pointed_dripstone_down_frustum": "#534239",
	"pointed_dripstone_down_merge": "#2e2520",
	"pointed_dripstone_down_middle": "#5e4b41",
	"pointed_dripstone_up_base": "#745c50",
	"pointed_dripstone_up_frustum": "#534239",
	"pointed_dripstone_up_merge": "#2e2520",
	"pointed_dripstone_up_middle": "#5e4b41",
	"pointed_dripstone_up_tip": "#1c1613",
	"polished_andesite": "#848685",
	"polished_basalt": "#5d5d5f",
	"polished_blackstone": "#353038",
	"polished_blackstone_bricks": "#302a31",
	"polished_deepslate": "#484849",
	"polished_diorite": "#c0c1c2",
	"polished_granite": "#9a6a59",
	"polished_tuff": "#616863",
	"poppy": "#130b05",
	"potatoes": "#0c1507",
	"powder_snow": "#f8fdfd",
	"powered_rail": "#614931",
	"prismarine": "#639c97",
	"prismarine_bricks": "#63ab9e",
	"prize_pottery_pattern": "#6b3e31",
	"pumpkin": "#bd751d",
	"pumpkin_stem_connected": "#111111",
	"pumpkin_stem_disconnected": "#151515",
	"purple_candle": "#7e7781",
	"purple_concrete": "#641f9c",
	"purple_concrete_powder": "#8337b1",
	"purple_coral_block": "#b720b4",
	"purple_glass": "#7f3fb2",
	"purple_glass_pane": "#7a3dab",
	"purple_glazed_terracotta": "#6d3098",
	"purple_shulker_box": "#67209c",
	"purple_terracotta": "#764656",
	"purple_wool": "#792aac",
	"purpur_block": "#a97da9",
	"purpur_pillar": "#ab80ab",
	"quartz_block": "#ebe5de",
	"quartz_bricks": "#eae5dd",
	"quartz_pillar": "#ebe5df",
	"rail": "#3e372b",
	"raw_copper_block": "#9a694f",
	"raw_gold_block": "#dda92e",
	"raw_iron_block": "#a6876b",
	"reactor_core": "#5d4853",
	"red_candle": "#827978",
	"red_concrete": "#8e2020",
	"red_concrete_powder": "#a83632",
	"red_coral_block": "#a22330",
	"red_flower": "#575d54",
	"red_glass": "#993333",
	"red_glass_pane": "#933030",
	"red_glazed_terracotta": "#b53b35",
	"red_mushroom_block": "#c82e2d",
	"red_nether_brick": "#450709",
	"red_sand": "#be6621",
	"red_sandstone": "#b8621d",
	"red_shulker_box": "#8c1f1e",
	"red_terracotta": "#8f3d2e",
	"red_tulip": "#131907",
	"red_wool": "#a02722",
	"redstone_block": "#af1805",
	"redstone_dust_line": "#d2d2d2",
	"redstone_lamp": "#764d2d",
	"redstone_ore": "#8c6d6d",
	"redstone_torch": "#0c0603",
	"redstone_wire": "#b9b9b9",
	"reinforced_deepslate": "#575b55",
	"repeater": "#a49d9c",
	"repeating_command_block": "#806eaa",
	"repeating_command_block_conditional": "#7f6dab",
	"resin_block": "#d96319",
	"resin_bricks": "#cd5818",
	"resin_clump": "#180c02",
	"respawn_anchor": "#2f1257",
	"respawn_anchor_side0": "#27173e",
	"respawn_anchor_side1": "#2a1a40",
	"respawn_anchor_side2": "#2c1c41",
	"respawn_anchor_side3": "#2f1e42",
	"respawn_anchor_side4": "#312044",
	"rooted_dirt": "#90674c",
	"sand": "#dbcfa3",
	"sandstone": "#dace9f",
	"sapling": "#282b19",
	"scrape_pottery_pattern": "#6e4032",
	"sculk": "#0c1d24",
	"sculk_catalyst": "#364b4c",
	"sculk_sensor": "#08262e",
	"sculk_sensor_tendril": "#010b0c",
	"sculk_shrieker": "#223130",
	"sculk_shrieker_can_summon": "#1e4042",
	"sculk_vein": "#052128",
	"sea_lantern": "#acc7be",
	"sea_pickle": "#707645",
	"seagrass": "#3f632d",
	"sheaf_pottery_pattern": "#6d3f31",
	"shelter_pottery_pattern": "#6e3f32",
	"short_dry_grass": "#231d14",
	"shroomlight": "#f09246",
	"shulker_box": "#7a6362",
	"silver_concrete": "#7d7d73",
	"silver_concrete_powder": "#9a9a94",
	"silver_glass": "#999999",
	"silver_glass_pane": "#939393",
	"silver_glazed_terracotta": "#90a6a7",
	"silver_shulker_box": "#7c7c73",
	"silver_terracotta": "#876a61",
	"silver_wool": "#8e8e86",
	"skull_pottery_pattern": "#6c3e31",
	"slime_block": "#6fc05b",
	"small_amethyst_bud": "#100c18",
	"small_dripleaf": "#0c0f05",
	"small_dripleaf_stem": "#0e1206",
	"smithing_table": "#3a2729",
	"smoker": "#635a4c",
	"smooth_basalt": "#48484e",
	"smooth_red_sandstone": "#bd651f",
	"smooth_sandstone": "#d9ce9f",
	"sniffer_egg": "#40271c",
	"sniffer_egg_not_cracked_east": "#463624",
	"sniffer_egg_not_cracked_north": "#50432c",
	"sniffer_egg_not_cracked_south": "#51442d",
	"sniffer_egg_not_cracked_west": "#433a26",
	"sniffer_egg_slightly_cracked_east": "#433323",
	"sniffer_egg_slightly_cracked_north": "#4e3f2b",
	"sniffer_egg_slightly_cracked_south": "#4e3f2b",
	"sniffer_egg_slightly_cracked_west": "#423926",
	"sniffer_egg_very_cracked_east": "#403022",
	"sniffer_egg_very_cracked_north": "#4a3b29",
	"sniffer_egg_very_cracked_south": "#4a3c29",
	"sniffer_egg_very_cracked_west": "#3e3524",
	"snort_pottery_pattern": "#693c2f",
	"snow": "#a99785",
	"snow_block": "#f9fefe",
	"soul_campfire": "#366666",
	"soul_fire": "#30a0a0",
	"soul_lantern": "#1d292f",
	"soul_sand": "#513e32",
	"soul_soil": "#4b392e",
	"soul_torch": "#080807",
	"spawner": "#191f2b",
	"sponge": "#c3c04a",
	"spore_blossom": "#67304f",
	"spore_blossom_base": "#46581f",
	"spruce_door": "#695030",
	"spruce_leaves": "#676767",
	"spruce_log": "#533a1f",
	"spruce_planks": "#725430",
	"spruce_sapling": "#0e130b",
	"spruce_trapdoor": "#674f2f",
	"stained_glass": "#897774",
	"stained_hardened_clay": "#745446",
	"sticky_piston": "#7a955c",
	"stone": "#7d7d7d",
	"stone_bricks": "#7a797a",
	"stone_slab": "#918a82",
	"stonecutter": "#6e6f6f",
	"stonecutter2": "#645f5a",
	"stonecutter_other": "#717171",
	"stripped_acacia_log": "#aa5b37",
	"stripped_bamboo_block": "#b9a54c",
	"stripped_birch_log": "#c1ad75",
	"stripped_cherry_log": "#da9a98",
	"stripped_crimson_stem": "#813856",
	"stripped_dark_oak_log": "#44321d",
	"stripped_jungle_log": "#a87f52",
	"stripped_mangrove_log": "#72302d",
	"stripped_oak_log": "#a88851",
	"stripped_pale_oak_log": "#f0e8e6",
	"stripped_spruce_log": "#5c4628",
	"stripped_warped_stem": "#368b87",
	"suspicious_gravel": "#7e7979",
	"suspicious_sand": "#d6c798",
	"sweet_berry_bush": "#1b2a1a",
	"tall_dry_grass": "#524733",
	"tallgrass": "#6b5f54",
	"target": "#e3ada2",
	"terracotta": "#985e43",
	"tinted_glass": "#2b262d",
	"tnt": "#a3483f",
	"torch": "#0a0804",
	"torchflower": "#26261d",
	"torchflower_crop": "#09130d",
	"trapdoor": "#7b5e3f",
	"trapped_chest": "#7b5a27",
	"trial_spawner": "#2b3c49",
	"trial_spawner_top_open": "#2e333c",
	"tuff": "#6c6d66",
	"tuff_bricks": "#62665f",
	"turtle_egg": "#c2c1ad",
	"twisting_vines": "#062b26",
	"undyed_shulker_box": "#8b608b",
	"vault": "#2f383d",
	"verdant_froglight": "#dcefda",
	"vine": "#424242",
	"warped_door": "#2b7a74",
	"warped_fungus": "#0e1511",
	"warped_nylium": "#395750",
	"warped_planks": "#2b6863",
	"warped_roots": "#062b27",
	"warped_stem": "#37535d",
	"warped_trapdoor": "#255d57",
	"warped_wart_block": "#167779",
	"water": "#3050a0",
	"waterlily": "#4e4e4e",
	"weathered_chiseled_copper": "#68966f",
	"weathered_copper": "#6c996e",
	"weathered_copper_bars": "#26372a",
	"weathered_copper_bulb": "#7c8c62",
	"weathered_copper_chain1": "#080c0a",
	"weathered_copper_chain2": "#070b09",
	"weathered_copper_chest_inventory": "#69946b",
	"weathered_copper_door": "#62845f",
	"weathered_copper_grate": "#4a6a4d",
	"weathered_copper_lantern": "#273729",
	"weathered_copper_trapdoor": "#567a57",
	"weathered_cut_copper": "#6d916b",
	"weathered_lightning_rod": "#ced5cf",
	"web": "#5d5f60",
	"weeping_vines": "#0a0002",
	"weeping_vines_base": "#3b0812",
	"weeping_vines_plant": "#3b0705",
	"wet_sponge": "#abb546",
	"wheat": "#182509",
	"white_candle": "#868685",
	"white_concrete": "#cfd5d6",
	"white_concrete_powder": "#e1e3e3",
	"white_glass": "#ffffff",
	"white_glass_pane": "#f6f6f6",
	"white_glazed_terracotta": "#bcd4ca",
	"white_shulker_box": "#d7dcdd",
	"white_terracotta": "#d1b2a1",
	"white_tulip": "#131f0f",
	"white_wool": "#e9ecec",
	"wildflowers": "#38321b",
	"wildflowers_stem": "#010101",
	"wither_rose": "#060803",
	"wood": "#856f4d",
	"wood_door": "#7e6339",
	"wooden_door": "#846546",
	"wooden_slab": "#9c8152",
	"wool": "#826e67",
	"yellow_candle": "#86837a",
	"yellow_concrete": "#f0af15",
	"yellow_concrete_powder": "#e8c736",
	"yellow_coral_block": "#d8c742",
	"yellow_glass": "#e5e533",
	"yellow_glass_pane": "#dddd30",
	"yellow_glazed_terracotta": "#eac058",
	"yellow_shulker_box": "#f8bc1d",
	"yellow_terracotta": "#ba8523",
	"yellow_wool": "#f8c527",
}

func init() {
	// Add minecraft: prefixed aliases
	textureColorMap["minecraft:acacia_door"] = "#76422a"
	textureColorMap["minecraft:acacia_leaves"] = "#838282"
	textureColorMap["minecraft:acacia_log"] = "#7e5c46"
	textureColorMap["minecraft:acacia_planks"] = "#a85a32"
	textureColorMap["minecraft:acacia_sapling"] = "#33330a"
	textureColorMap["minecraft:acacia_trapdoor"] = "#774227"
	textureColorMap["minecraft:activator_rail"] = "#4e352d"
	textureColorMap["minecraft:allium"] = "#23222c"
	textureColorMap["minecraft:amethyst_block"] = "#8561bf"
	textureColorMap["minecraft:amethyst_cluster"] = "#594571"
	textureColorMap["minecraft:ancient_debris"] = "#5e4038"
	textureColorMap["minecraft:andesite"] = "#888888"
	textureColorMap["minecraft:angler_pottery_pattern"] = "#6e3f32"
	textureColorMap["minecraft:anvil"] = "#323232"
	textureColorMap["minecraft:archer_pottery_pattern"] = "#6c3e31"
	textureColorMap["minecraft:arms_up_pottery_pattern"] = "#6d3f32"
	textureColorMap["minecraft:azalea"] = "#4a5b23"
	textureColorMap["minecraft:azalea_leaves"] = "#4b6026"
	textureColorMap["minecraft:azalea_leaves_flowers"] = "#4f5830"
	textureColorMap["minecraft:azure_bluet"] = "#273026"
	textureColorMap["minecraft:bamboo_block"] = "#858e3b"
	textureColorMap["minecraft:bamboo_door"] = "#b19e4b"
	textureColorMap["minecraft:bamboo_fence"] = "#8a7c3b"
	textureColorMap["minecraft:bamboo_fence_gate"] = "#524a22"
	textureColorMap["minecraft:bamboo_leaf"] = "#7cc72b"
	textureColorMap["minecraft:bamboo_mosaic"] = "#beaa4e"
	textureColorMap["minecraft:bamboo_planks"] = "#c1ad50"
	textureColorMap["minecraft:bamboo_sapling"] = "#d6d7c9"
	textureColorMap["minecraft:bamboo_singleleaf"] = "#f0f4ea"
	textureColorMap["minecraft:bamboo_small_leaf"] = "#94bf67"
	textureColorMap["minecraft:bamboo_stem"] = "#5d9013"
	textureColorMap["minecraft:bamboo_trapdoor"] = "#a49446"
	textureColorMap["minecraft:barrel"] = "#765834"
	textureColorMap["minecraft:barrel_top_open"] = "#5c4322"
	textureColorMap["minecraft:barrier"] = "#610000"
	textureColorMap["minecraft:basalt"] = "#4c4c51"
	textureColorMap["minecraft:beacon"] = "#75dcd7"
	textureColorMap["minecraft:bed_feet"] = "#611410"
	textureColorMap["minecraft:bed_feet_end"] = "#39160c"
	textureColorMap["minecraft:bed_head"] = "#764e4b"
	textureColorMap["minecraft:bed_head_end"] = "#4e473e"
	textureColorMap["minecraft:bedrock"] = "#555555"
	textureColorMap["minecraft:bee_nest"] = "#bb914d"
	textureColorMap["minecraft:beehive"] = "#a4834d"
	textureColorMap["minecraft:beetroots"] = "#121b08"
	textureColorMap["minecraft:bell"] = "#f8e98a"
	textureColorMap["minecraft:big_dripleaf"] = "#65802e"
	textureColorMap["minecraft:big_dripleaf_side1"] = "#000100"
	textureColorMap["minecraft:big_dripleaf_side2"] = "#0f1307"
	textureColorMap["minecraft:big_dripleaf_stem"] = "#1d250f"
	textureColorMap["minecraft:birch_door"] = "#d6c9a0"
	textureColorMap["minecraft:birch_leaves"] = "#797779"
	textureColorMap["minecraft:birch_log"] = "#ccc5ac"
	textureColorMap["minecraft:birch_planks"] = "#c0af79"
	textureColorMap["minecraft:birch_sapling"] = "#303d1e"
	textureColorMap["minecraft:birch_trapdoor"] = "#cfc29d"
	textureColorMap["minecraft:black_candle"] = "#797879"
	textureColorMap["minecraft:black_concrete"] = "#080a0f"
	textureColorMap["minecraft:black_concrete_powder"] = "#191a1f"
	textureColorMap["minecraft:black_glass"] = "#191919"
	textureColorMap["minecraft:black_glass_pane"] = "#181818"
	textureColorMap["minecraft:black_glazed_terracotta"] = "#431e20"
	textureColorMap["minecraft:black_shulker_box"] = "#19191d"
	textureColorMap["minecraft:black_terracotta"] = "#251610"
	textureColorMap["minecraft:black_wool"] = "#141519"
	textureColorMap["minecraft:blackstone"] = "#2a2328"
	textureColorMap["minecraft:blade_pottery_pattern"] = "#714133"
	textureColorMap["minecraft:blast_furnace"] = "#666564"
	textureColorMap["minecraft:blue_candle"] = "#797b82"
	textureColorMap["minecraft:blue_concrete"] = "#2c2e8f"
	textureColorMap["minecraft:blue_concrete_powder"] = "#4649a6"
	textureColorMap["minecraft:blue_coral_block"] = "#3157ce"
	textureColorMap["minecraft:blue_glass"] = "#334cb2"
	textureColorMap["minecraft:blue_glass_pane"] = "#3049ab"
	textureColorMap["minecraft:blue_glazed_terracotta"] = "#2f408b"
	textureColorMap["minecraft:blue_ice"] = "#74a7fd"
	textureColorMap["minecraft:blue_orchid"] = "#071515"
	textureColorMap["minecraft:blue_shulker_box"] = "#2b2d8c"
	textureColorMap["minecraft:blue_terracotta"] = "#4a3b5b"
	textureColorMap["minecraft:blue_wool"] = "#35399d"
	textureColorMap["minecraft:bone_block"] = "#dbd7c1"
	textureColorMap["minecraft:bookshelf"] = "#755e3b"
	textureColorMap["minecraft:border"] = "#b5392f"
	textureColorMap["minecraft:brewer_pottery_pattern"] = "#6e3f32"
	textureColorMap["minecraft:brewing_stand"] = "#584e49"
	textureColorMap["minecraft:brick"] = "#966153"
	textureColorMap["minecraft:brown_candle"] = "#7f7b78"
	textureColorMap["minecraft:brown_concrete"] = "#603b1f"
	textureColorMap["minecraft:brown_concrete_powder"] = "#7d5435"
	textureColorMap["minecraft:brown_glass"] = "#664c33"
	textureColorMap["minecraft:brown_glass_pane"] = "#614930"
	textureColorMap["minecraft:brown_glazed_terracotta"] = "#776a55"
	textureColorMap["minecraft:brown_mushroom_block"] = "#956f51"
	textureColorMap["minecraft:brown_shulker_box"] = "#6a4223"
	textureColorMap["minecraft:brown_terracotta"] = "#4d3323"
	textureColorMap["minecraft:brown_wool"] = "#724728"
	textureColorMap["minecraft:budding_amethyst"] = "#8460ba"
	textureColorMap["minecraft:burn_pottery_pattern"] = "#6f4032"
	textureColorMap["minecraft:cactus"] = "#4b2b30"
	textureColorMap["minecraft:cake"] = "#6d5042"
	textureColorMap["minecraft:calcite"] = "#dfe0dc"
	textureColorMap["minecraft:calibrated_sculk_sensor"] = "#1b4f64"
	textureColorMap["minecraft:calibrated_sculk_sensor_amethyst"] = "#312838"
	textureColorMap["minecraft:calibrated_sculk_sensor_input"] = "#1d2232"
	textureColorMap["minecraft:camera"] = "#534229"
	textureColorMap["minecraft:campfire"] = "#5d4b2d"
	textureColorMap["minecraft:candle"] = "#878581"
	textureColorMap["minecraft:carpet"] = "#826e67"
	textureColorMap["minecraft:carrots"] = "#13210a"
	textureColorMap["minecraft:cartography_table"] = "#675743"
	textureColorMap["minecraft:cartography_table_side1"] = "#463222"
	textureColorMap["minecraft:cartography_table_side2"] = "#513d2a"
	textureColorMap["minecraft:cartography_table_side3"] = "#432b14"
	textureColorMap["minecraft:cauldron"] = "#2d2c2e"
	textureColorMap["minecraft:cauldron_water"] = "#cdcdcd"
	textureColorMap["minecraft:cave_vines_body"] = "#393e17"
	textureColorMap["minecraft:cave_vines_head"] = "#373f17"
	textureColorMap["minecraft:chain1"] = "#050608"
	textureColorMap["minecraft:chain2"] = "#050607"
	textureColorMap["minecraft:chain_command_block"] = "#83a193"
	textureColorMap["minecraft:chain_command_block_conditional"] = "#81a193"
	textureColorMap["minecraft:cherry_door"] = "#cfa09a"
	textureColorMap["minecraft:cherry_leaves"] = "#d199af"
	textureColorMap["minecraft:cherry_log"] = "#77575a"
	textureColorMap["minecraft:cherry_planks"] = "#e2b2ac"
	textureColorMap["minecraft:cherry_sapling"] = "#4e3844"
	textureColorMap["minecraft:cherry_trapdoor"] = "#c29994"
	textureColorMap["minecraft:chest"] = "#7d5b26"
	textureColorMap["minecraft:chiseled_bookshelf"] = "#927557"
	textureColorMap["minecraft:chiseled_bookshelf_empty"] = "#5a4629"
	textureColorMap["minecraft:chiseled_bookshelf_occupied"] = "#795e45"
	textureColorMap["minecraft:chiseled_copper"] = "#b86449"
	textureColorMap["minecraft:chiseled_deepslate"] = "#363636"
	textureColorMap["minecraft:chiseled_nether_bricks"] = "#2d161b"
	textureColorMap["minecraft:chiseled_polished_blackstone"] = "#353038"
	textureColorMap["minecraft:chiseled_quartz_block"] = "#e7e2d9"
	textureColorMap["minecraft:chiseled_red_sandstone"] = "#b7601b"
	textureColorMap["minecraft:chiseled_resin_bricks"] = "#c85418"
	textureColorMap["minecraft:chiseled_sandstone"] = "#d8ca9b"
	textureColorMap["minecraft:chiseled_stone_bricks"] = "#777677"
	textureColorMap["minecraft:chiseled_tuff"] = "#5b6058"
	textureColorMap["minecraft:chiseled_tuff_bricks"] = "#686c64"
	textureColorMap["minecraft:chorus_flower"] = "#977897"
	textureColorMap["minecraft:chorus_flower_dead"] = "#603d5e"
	textureColorMap["minecraft:chorus_plant"] = "#5d395d"
	textureColorMap["minecraft:clay"] = "#a0a6b3"
	textureColorMap["minecraft:coal_block"] = "#100f0f"
	textureColorMap["minecraft:coal_ore"] = "#696969"
	textureColorMap["minecraft:coarse_dirt"] = "#77553b"
	textureColorMap["minecraft:cobbled_deepslate"] = "#4d4d50"
	textureColorMap["minecraft:cobblestone"] = "#7f7f7f"
	textureColorMap["minecraft:cocoa"] = "#332411"
	textureColorMap["minecraft:command_block"] = "#b1866b"
	textureColorMap["minecraft:comparator"] = "#aaa09e"
	textureColorMap["minecraft:composter"] = "#6c4621"
	textureColorMap["minecraft:concrete"] = "#725c5b"
	textureColorMap["minecraft:concretePowder"] = "#877870"
	textureColorMap["minecraft:conduit_base"] = "#a58c71"
	textureColorMap["minecraft:conduit_cage"] = "#bca994"
	textureColorMap["minecraft:conduit_closed"] = "#125770"
	textureColorMap["minecraft:conduit_open"] = "#24657c"
	textureColorMap["minecraft:conduit_wind_horizontal"] = "#fefefe"
	textureColorMap["minecraft:conduit_wind_vertical"] = "#fefefe"
	textureColorMap["minecraft:copper_bars"] = "#462419"
	textureColorMap["minecraft:copper_block"] = "#c06b4f"
	textureColorMap["minecraft:copper_bulb"] = "#b97551"
	textureColorMap["minecraft:copper_chain1"] = "#110906"
	textureColorMap["minecraft:copper_chain2"] = "#0f0805"
	textureColorMap["minecraft:copper_chest_inventory"] = "#bc694d"
	textureColorMap["minecraft:copper_door"] = "#a85f48"
	textureColorMap["minecraft:copper_grate"] = "#864b37"
	textureColorMap["minecraft:copper_lantern"] = "#412c1f"
	textureColorMap["minecraft:copper_ore"] = "#7c7d78"
	textureColorMap["minecraft:copper_torch"] = "#090805"
	textureColorMap["minecraft:copper_trapdoor"] = "#97543f"
	textureColorMap["minecraft:coral"] = "#a35883"
	textureColorMap["minecraft:coral_block"] = "#92697d"
	textureColorMap["minecraft:cornflower"] = "#e7ecf0"
	textureColorMap["minecraft:cracked_deepslate_bricks"] = "#404041"
	textureColorMap["minecraft:cracked_deepslate_tiles"] = "#343434"
	textureColorMap["minecraft:cracked_nether_bricks"] = "#281417"
	textureColorMap["minecraft:cracked_polished_blackstone_bricks"] = "#2c252b"
	textureColorMap["minecraft:cracked_stone_bricks"] = "#767576"
	textureColorMap["minecraft:crafter"] = "#6e5d5e"
	textureColorMap["minecraft:crafter_east"] = "#7f725d"
	textureColorMap["minecraft:crafter_north"] = "#6c655b"
	textureColorMap["minecraft:crafter_south"] = "#7c7060"
	textureColorMap["minecraft:crafter_west"] = "#81735e"
	textureColorMap["minecraft:crafting_table"] = "#7d5d3a"
	textureColorMap["minecraft:creaking_heart"] = "#6e4632"
	textureColorMap["minecraft:crimson_door"] = "#72364f"
	textureColorMap["minecraft:crimson_fungus"] = "#210a06"
	textureColorMap["minecraft:crimson_log"] = "#662531"
	textureColorMap["minecraft:crimson_nylium"] = "#761c1c"
	textureColorMap["minecraft:crimson_planks"] = "#653046"
	textureColorMap["minecraft:crimson_roots"] = "#25020c"
	textureColorMap["minecraft:crimson_trapdoor"] = "#572a3d"
	textureColorMap["minecraft:crying_obsidian"] = "#200a3c"
	textureColorMap["minecraft:cut_copper"] = "#bf6a50"
	textureColorMap["minecraft:cyan_candle"] = "#77807f"
	textureColorMap["minecraft:cyan_concrete"] = "#157788"
	textureColorMap["minecraft:cyan_concrete_powder"] = "#24939d"
	textureColorMap["minecraft:cyan_glass"] = "#4c7f99"
	textureColorMap["minecraft:cyan_glass_pane"] = "#497a93"
	textureColorMap["minecraft:cyan_glazed_terracotta"] = "#34767d"
	textureColorMap["minecraft:cyan_shulker_box"] = "#147987"
	textureColorMap["minecraft:cyan_terracotta"] = "#565b5b"
	textureColorMap["minecraft:cyan_wool"] = "#158991"
	textureColorMap["minecraft:dandelion"] = "#121505"
	textureColorMap["minecraft:danger_pottery_pattern"] = "#6f4032"
	textureColorMap["minecraft:dark_oak_door"] = "#4a3218"
	textureColorMap["minecraft:dark_oak_leaves"] = "#8a898a"
	textureColorMap["minecraft:dark_oak_log"] = "#3f2d18"
	textureColorMap["minecraft:dark_oak_planks"] = "#422b14"
	textureColorMap["minecraft:dark_oak_sapling"] = "#1a260d"
	textureColorMap["minecraft:dark_oak_trapdoor"] = "#4b3117"
	textureColorMap["minecraft:dark_prismarine"] = "#335b4b"
	textureColorMap["minecraft:daylight_detector"] = "#625540"
	textureColorMap["minecraft:daylight_detector_inverted"] = "#6a6d70"
	textureColorMap["minecraft:dead_blue_coral_block"] = "#827b77"
	textureColorMap["minecraft:dead_bush"] = "#2d2923"
	textureColorMap["minecraft:dead_pink_coral_block"] = "#7c7572"
	textureColorMap["minecraft:dead_purple_coral_block"] = "#837b77"
	textureColorMap["minecraft:dead_red_coral_block"] = "#837b77"
	textureColorMap["minecraft:dead_yellow_coral_block"] = "#857e7a"
	textureColorMap["minecraft:decorated_pot"] = "#713f33"
	textureColorMap["minecraft:decorated_pot_base"] = "#573027"
	textureColorMap["minecraft:deepslate"] = "#535355"
	textureColorMap["minecraft:deepslate_bricks"] = "#464647"
	textureColorMap["minecraft:deepslate_coal_ore"] = "#4a4a4c"
	textureColorMap["minecraft:deepslate_copper_ore"] = "#5c5d59"
	textureColorMap["minecraft:deepslate_diamond_ore"] = "#536a6a"
	textureColorMap["minecraft:deepslate_emerald_ore"] = "#4e6857"
	textureColorMap["minecraft:deepslate_gold_ore"] = "#73664e"
	textureColorMap["minecraft:deepslate_iron_ore"] = "#6a635e"
	textureColorMap["minecraft:deepslate_lapis_ore"] = "#4f5a73"
	textureColorMap["minecraft:deepslate_redstone_ore"] = "#68494a"
	textureColorMap["minecraft:deepslate_tiles"] = "#363637"
	textureColorMap["minecraft:detector_rail"] = "#4e3e36"
	textureColorMap["minecraft:diamond_block"] = "#62ede4"
	textureColorMap["minecraft:diamond_ore"] = "#798d8c"
	textureColorMap["minecraft:diorite"] = "#bcbcbc"
	textureColorMap["minecraft:dirt"] = "#866043"
	textureColorMap["minecraft:dirt_path"] = "#8a6b3f"
	textureColorMap["minecraft:dispenser"] = "#7a7979"
	textureColorMap["minecraft:dispenser_front_vertical"] = "#626161"
	textureColorMap["minecraft:double_stone_slab"] = "#918a82"
	textureColorMap["minecraft:dragon_egg"] = "#0c090f"
	textureColorMap["minecraft:dried_ghast_state"] = "#464444"
	textureColorMap["minecraft:dried_ghast_state_1_left"] = "#3c3737"
	textureColorMap["minecraft:dried_ghast_state_1_right"] = "#3c3737"
	textureColorMap["minecraft:dried_ghast_state_1_tentacles"] = "#777474"
	textureColorMap["minecraft:dried_ghast_state_2_left"] = "#444141"
	textureColorMap["minecraft:dried_ghast_state_2_right"] = "#444141"
	textureColorMap["minecraft:dried_ghast_state_2_tentacles"] = "#918e8e"
	textureColorMap["minecraft:dried_ghast_state_3_left"] = "#4d4a4a"
	textureColorMap["minecraft:dried_ghast_state_3_right"] = "#4d4a4a"
	textureColorMap["minecraft:dried_ghast_state_3_tentacles"] = "#aba8a8"
	textureColorMap["minecraft:dried_ghast_state_4_left"] = "#5d5d5d"
	textureColorMap["minecraft:dried_ghast_state_4_right"] = "#5d5d5d"
	textureColorMap["minecraft:dried_ghast_state_4_tentacles"] = "#dfdddd"
	textureColorMap["minecraft:dried_kelp"] = "#323a26"
	textureColorMap["minecraft:dried_kelp_side_a"] = "#26301d"
	textureColorMap["minecraft:dried_kelp_side_b"] = "#26301d"
	textureColorMap["minecraft:dripstone_block"] = "#866b5c"
	textureColorMap["minecraft:dropper"] = "#7a7979"
	textureColorMap["minecraft:dropper_front_vertical"] = "#616060"
	textureColorMap["minecraft:emerald_block"] = "#2acb57"
	textureColorMap["minecraft:emerald_ore"] = "#6c8873"
	textureColorMap["minecraft:enchanting_table"] = "#3c2732"
	textureColorMap["minecraft:end_rod"] = "#2f2c2a"
	textureColorMap["minecraft:end_stone"] = "#dbde9e"
	textureColorMap["minecraft:end_stone_bricks"] = "#dae0a2"
	textureColorMap["minecraft:ender_chest"] = "#1d2c2d"
	textureColorMap["minecraft:endframe"] = "#6a7e62"
	textureColorMap["minecraft:endframe_eye"] = "#0d1a17"
	textureColorMap["minecraft:explorer_pottery_pattern"] = "#693d30"
	textureColorMap["minecraft:exposed_chiseled_copper"] = "#9a7764"
	textureColorMap["minecraft:exposed_copper"] = "#a17d67"
	textureColorMap["minecraft:exposed_copper_bars"] = "#3c3028"
	textureColorMap["minecraft:exposed_copper_bulb"] = "#a57d5e"
	textureColorMap["minecraft:exposed_copper_chain1"] = "#0e0b09"
	textureColorMap["minecraft:exposed_copper_chain2"] = "#0d0a08"
	textureColorMap["minecraft:exposed_copper_chest_inventory"] = "#a17967"
	textureColorMap["minecraft:exposed_copper_door"] = "#8e6d5d"
	textureColorMap["minecraft:exposed_copper_grate"] = "#715849"
	textureColorMap["minecraft:exposed_copper_lantern"] = "#3d362b"
	textureColorMap["minecraft:exposed_copper_trapdoor"] = "#806353"
	textureColorMap["minecraft:exposed_cut_copper"] = "#9a7965"
	textureColorMap["minecraft:exposed_lightning_rod"] = "#d8d2cf"
	textureColorMap["minecraft:eyeblossom"] = "#161414"
	textureColorMap["minecraft:eyeblossom_blooming"] = "#1f1c1b"
	textureColorMap["minecraft:eyeblossom_eyes_blooming"] = "#030200"
	textureColorMap["minecraft:eyeblossom_stem_blooming"] = "#1c1a1a"
	textureColorMap["minecraft:farmland"] = "#70492a"
	textureColorMap["minecraft:fence"] = "#9c8152"
	textureColorMap["minecraft:fence_gate"] = "#9c8152"
	textureColorMap["minecraft:firefly_bush"] = "#1b1a0d"
	textureColorMap["minecraft:fletcher_table"] = "#c5b485"
	textureColorMap["minecraft:fletcher_table_side1"] = "#bfa781"
	textureColorMap["minecraft:fletcher_table_side2"] = "#ad9b6f"
	textureColorMap["minecraft:flow_pottery_pattern"] = "#6c3e31"
	textureColorMap["minecraft:flower"] = "#454b43"
	textureColorMap["minecraft:flowering_azalea"] = "#595e36"
	textureColorMap["minecraft:flowering_azalea_leaves"] = "#5b6838"
	textureColorMap["minecraft:friend_pottery_pattern"] = "#6d3f31"
	textureColorMap["minecraft:frogspawn"] = "#221e1b"
	textureColorMap["minecraft:frosted_ice"] = "#8ab3fc"
	textureColorMap["minecraft:furnace"] = "#6e6c67"
	textureColorMap["minecraft:gilded_blackstone"] = "#372a26"
	textureColorMap["minecraft:glass"] = "#8c9597"
	textureColorMap["minecraft:glass_pane"] = "#aad2d9"
	textureColorMap["minecraft:glow_item_frame"] = "#946740"
	textureColorMap["minecraft:glow_lichen"] = "#2e3531"
	textureColorMap["minecraft:glowing_obsidian"] = "#50020c"
	textureColorMap["minecraft:glowstone"] = "#ab8354"
	textureColorMap["minecraft:gold_block"] = "#f6d03d"
	textureColorMap["minecraft:gold_ore"] = "#91856a"
	textureColorMap["minecraft:granite"] = "#956755"
	textureColorMap["minecraft:grass"] = "#727272"
	textureColorMap["minecraft:grass_block"] = "#a99685"
	textureColorMap["minecraft:gravel"] = "#837f7e"
	textureColorMap["minecraft:gray_candle"] = "#7c7d7d"
	textureColorMap["minecraft:gray_concrete"] = "#36393d"
	textureColorMap["minecraft:gray_concrete_powder"] = "#4c5154"
	textureColorMap["minecraft:gray_glass"] = "#4c4c4c"
	textureColorMap["minecraft:gray_glass_pane"] = "#494949"
	textureColorMap["minecraft:gray_glazed_terracotta"] = "#535a5d"
	textureColorMap["minecraft:gray_shulker_box"] = "#373a3e"
	textureColorMap["minecraft:gray_terracotta"] = "#392a23"
	textureColorMap["minecraft:gray_wool"] = "#3e4447"
	textureColorMap["minecraft:green_candle"] = "#7c7d76"
	textureColorMap["minecraft:green_concrete"] = "#495b24"
	textureColorMap["minecraft:green_concrete_powder"] = "#61772c"
	textureColorMap["minecraft:green_glass"] = "#667f33"
	textureColorMap["minecraft:green_glass_pane"] = "#617a30"
	textureColorMap["minecraft:green_glazed_terracotta"] = "#758e43"
	textureColorMap["minecraft:green_shulker_box"] = "#4f641f"
	textureColorMap["minecraft:green_terracotta"] = "#4c532a"
	textureColorMap["minecraft:green_wool"] = "#546d1b"
	textureColorMap["minecraft:guster_pottery_pattern"] = "#6f4032"
	textureColorMap["minecraft:hanging_roots"] = "#2f211a"
	textureColorMap["minecraft:hay_block"] = "#a58919"
	textureColorMap["minecraft:heart_pottery_pattern"] = "#6b3d30"
	textureColorMap["minecraft:heartbreak_pottery_pattern"] = "#6c3e31"
	textureColorMap["minecraft:heavy_core"] = "#3d4046"
	textureColorMap["minecraft:honey_block"] = "#f7ad2a"
	textureColorMap["minecraft:honeycomb"] = "#e5941d"
	textureColorMap["minecraft:hopper"] = "#353537"
	textureColorMap["minecraft:howl_pottery_pattern"] = "#6d3f32"
	textureColorMap["minecraft:ice"] = "#91b7fd"
	textureColorMap["minecraft:iron_bars"] = "#3e3f3d"
	textureColorMap["minecraft:iron_block"] = "#dcdcdc"
	textureColorMap["minecraft:iron_door"] = "#b0afaf"
	textureColorMap["minecraft:iron_ore"] = "#88817a"
	textureColorMap["minecraft:iron_trapdoor"] = "#aeadad"
	textureColorMap["minecraft:itemframe_background"] = "#74432a"
	textureColorMap["minecraft:jack_o_lantern"] = "#d48020"
	textureColorMap["minecraft:jigsaw"] = "#3a313c"
	textureColorMap["minecraft:jigsaw_lock"] = "#2d262f"
	textureColorMap["minecraft:jukebox"] = "#5a3d2b"
	textureColorMap["minecraft:jungle_door"] = "#976d4c"
	textureColorMap["minecraft:jungle_leaves"] = "#8e8c85"
	textureColorMap["minecraft:jungle_log"] = "#75582f"
	textureColorMap["minecraft:jungle_planks"] = "#a07350"
	textureColorMap["minecraft:jungle_sapling"] = "#0f1b05"
	textureColorMap["minecraft:jungle_trapdoor"] = "#7f5c40"
	textureColorMap["minecraft:ladder"] = "#46361e"
	textureColorMap["minecraft:lantern"] = "#2b2522"
	textureColorMap["minecraft:lapis_block"] = "#1e438c"
	textureColorMap["minecraft:lapis_ore"] = "#6b758d"
	textureColorMap["minecraft:large_amethyst_bud"] = "#31263d"
	textureColorMap["minecraft:leaf_litter"] = "#4e4e4e"
	textureColorMap["minecraft:leaves"] = "#7c7a7a"
	textureColorMap["minecraft:leaves2"] = "#868586"
	textureColorMap["minecraft:lectern"] = "#9a7746"
	textureColorMap["minecraft:lectern_sides"] = "#957543"
	textureColorMap["minecraft:lever"] = "#080705"
	textureColorMap["minecraft:light_blue_candle"] = "#788185"
	textureColorMap["minecraft:light_blue_concrete"] = "#2389c6"
	textureColorMap["minecraft:light_blue_concrete_powder"] = "#4ab4d5"
	textureColorMap["minecraft:light_blue_glass"] = "#6699d8"
	textureColorMap["minecraft:light_blue_glass_pane"] = "#6193d0"
	textureColorMap["minecraft:light_blue_glazed_terracotta"] = "#5ea4d0"
	textureColorMap["minecraft:light_blue_shulker_box"] = "#31a3d4"
	textureColorMap["minecraft:light_blue_terracotta"] = "#716c89"
	textureColorMap["minecraft:light_blue_wool"] = "#3aafd9"
	textureColorMap["minecraft:light_gray_candle"] = "#7f7f7e"
	textureColorMap["minecraft:lightning_rod"] = "#221c19"
	textureColorMap["minecraft:lily_of_the_valley"] = "#dfebd8"
	textureColorMap["minecraft:lime_candle"] = "#7e8376"
	textureColorMap["minecraft:lime_concrete"] = "#5ea818"
	textureColorMap["minecraft:lime_concrete_powder"] = "#7dbd29"
	textureColorMap["minecraft:lime_glass"] = "#7fcc19"
	textureColorMap["minecraft:lime_glass_pane"] = "#7ac418"
	textureColorMap["minecraft:lime_glazed_terracotta"] = "#a2c537"
	textureColorMap["minecraft:lime_shulker_box"] = "#63ac17"
	textureColorMap["minecraft:lime_terracotta"] = "#677534"
	textureColorMap["minecraft:lime_wool"] = "#70b919"
	textureColorMap["minecraft:lodestone"] = "#858689"
	textureColorMap["minecraft:log"] = "#856f4d"
	textureColorMap["minecraft:log2"] = "#5e442f"
	textureColorMap["minecraft:loom"] = "#7f6346"
	textureColorMap["minecraft:magenta_candle"] = "#827981"
	textureColorMap["minecraft:magenta_concrete"] = "#a9309f"
	textureColorMap["minecraft:magenta_concrete_powder"] = "#c053b8"
	textureColorMap["minecraft:magenta_glass"] = "#b24cd8"
	textureColorMap["minecraft:magenta_glass_pane"] = "#ab49d0"
	textureColorMap["minecraft:magenta_glazed_terracotta"] = "#d064bf"
	textureColorMap["minecraft:magenta_shulker_box"] = "#ad36a3"
	textureColorMap["minecraft:magenta_terracotta"] = "#95586c"
	textureColorMap["minecraft:magenta_wool"] = "#bd44b3"
	textureColorMap["minecraft:magma"] = "#bc5020"
	textureColorMap["minecraft:magma_block"] = "#8e3f1f"
	textureColorMap["minecraft:mangrove_door"] = "#702f2e"
	textureColorMap["minecraft:mangrove_leaves"] = "#787777"
	textureColorMap["minecraft:mangrove_log"] = "#5c3929"
	textureColorMap["minecraft:mangrove_planks"] = "#753630"
	textureColorMap["minecraft:mangrove_propagule"] = "#0c160a"
	textureColorMap["minecraft:mangrove_propagule_hanging"] = "#161c0e"
	textureColorMap["minecraft:mangrove_roots"] = "#2e2417"
	textureColorMap["minecraft:mangrove_trapdoor"] = "#612825"
	textureColorMap["minecraft:medium_amethyst_bud"] = "#1f1828"
	textureColorMap["minecraft:melon"] = "#70911e"
	textureColorMap["minecraft:melon_stem_connected"] = "#121212"
	textureColorMap["minecraft:melon_stem_disconnected"] = "#151515"
	textureColorMap["minecraft:miner_pottery_pattern"] = "#6f4032"
	textureColorMap["minecraft:moss_block"] = "#596d2d"
	textureColorMap["minecraft:mossy_cobblestone"] = "#6e765e"
	textureColorMap["minecraft:mossy_stone_bricks"] = "#737969"
	textureColorMap["minecraft:mourner_pottery_pattern"] = "#6d3e31"
	textureColorMap["minecraft:mud"] = "#3c393c"
	textureColorMap["minecraft:mud_bricks"] = "#89674f"
	textureColorMap["minecraft:muddy_mangrove_roots"] = "#453a2e"
	textureColorMap["minecraft:mushroom_block"] = "#c9aa78"
	textureColorMap["minecraft:mushroom_brown"] = "#140f0c"
	textureColorMap["minecraft:mushroom_red"] = "#1b0908"
	textureColorMap["minecraft:mushroom_stem"] = "#cbc4b9"
	textureColorMap["minecraft:mycelium"] = "#705c56"
	textureColorMap["minecraft:nether_brick"] = "#2c151a"
	textureColorMap["minecraft:nether_gold_ore"] = "#73362a"
	textureColorMap["minecraft:nether_quartz_ore"] = "#75413e"
	textureColorMap["minecraft:nether_sprouts"] = "#021210"
	textureColorMap["minecraft:nether_wart"] = "#2f0707"
	textureColorMap["minecraft:nether_wart_block"] = "#720302"
	textureColorMap["minecraft:netherite_block"] = "#423d3f"
	textureColorMap["minecraft:netherrack"] = "#612626"
	textureColorMap["minecraft:note_block"] = "#583a28"
	textureColorMap["minecraft:oak_leaves"] = "#838183"
	textureColorMap["minecraft:oak_log"] = "#82673d"
	textureColorMap["minecraft:oak_planks"] = "#a2824e"
	textureColorMap["minecraft:oak_sapling"] = "#212e11"
	textureColorMap["minecraft:oak_trapdoor"] = "#6b5530"
	textureColorMap["minecraft:observer"] = "#535151"
	textureColorMap["minecraft:obsidian"] = "#0f0a18"
	textureColorMap["minecraft:ochre_froglight"] = "#f7efc1"
	textureColorMap["minecraft:orange_candle"] = "#877e76"
	textureColorMap["minecraft:orange_concrete"] = "#e06100"
	textureColorMap["minecraft:orange_concrete_powder"] = "#e3831f"
	textureColorMap["minecraft:orange_glass"] = "#d87f33"
	textureColorMap["minecraft:orange_glass_pane"] = "#d07a30"
	textureColorMap["minecraft:orange_glazed_terracotta"] = "#9a935b"
	textureColorMap["minecraft:orange_shulker_box"] = "#ea6a08"
	textureColorMap["minecraft:orange_terracotta"] = "#a15325"
	textureColorMap["minecraft:orange_tulip"] = "#1a2210"
	textureColorMap["minecraft:orange_wool"] = "#f07613"
	textureColorMap["minecraft:oxeye_daisy"] = "#303e26"
	textureColorMap["minecraft:oxidized_chiseled_copper"] = "#53a184"
	textureColorMap["minecraft:oxidized_copper"] = "#52a284"
	textureColorMap["minecraft:oxidized_copper_bars"] = "#1d372d"
	textureColorMap["minecraft:oxidized_copper_bulb"] = "#678e69"
	textureColorMap["minecraft:oxidized_copper_chain1"] = "#070d0b"
	textureColorMap["minecraft:oxidized_copper_chain2"] = "#060c0a"
	textureColorMap["minecraft:oxidized_copper_chest_inventory"] = "#509e84"
	textureColorMap["minecraft:oxidized_copper_door"] = "#488d75"
	textureColorMap["minecraft:oxidized_copper_grate"] = "#39705b"
	textureColorMap["minecraft:oxidized_copper_lantern"] = "#20392d"
	textureColorMap["minecraft:oxidized_copper_trapdoor"] = "#428069"
	textureColorMap["minecraft:oxidized_cut_copper"] = "#4f997e"
	textureColorMap["minecraft:oxidized_lightning_rod"] = "#0c1813"
	textureColorMap["minecraft:packed_ice"] = "#8db4fa"
	textureColorMap["minecraft:packed_mud"] = "#8e6a4f"
	textureColorMap["minecraft:pale_hanging_moss"] = "#2f312e"
	textureColorMap["minecraft:pale_hanging_moss_tip"] = "#212220"
	textureColorMap["minecraft:pale_moss"] = "#6a7068"
	textureColorMap["minecraft:pale_moss_block"] = "#6a7068"
	textureColorMap["minecraft:pale_moss_carpet_side_base"] = "#353835"
	textureColorMap["minecraft:pale_moss_carpet_side_tip"] = "#151715"
	textureColorMap["minecraft:pale_oak_door"] = "#cfc7c5"
	textureColorMap["minecraft:pale_oak_leaves"] = "#6a6f68"
	textureColorMap["minecraft:pale_oak_log"] = "#8e8583"
	textureColorMap["minecraft:pale_oak_planks"] = "#e3d9d8"
	textureColorMap["minecraft:pale_oak_sapling"] = "#2c2a28"
	textureColorMap["minecraft:pale_oak_trapdoor"] = "#e5dcda"
	textureColorMap["minecraft:pearlescent_froglight"] = "#f0e8e9"
	textureColorMap["minecraft:peony"] = "#36393d"
	textureColorMap["minecraft:pink_candle"] = "#867e80"
	textureColorMap["minecraft:pink_concrete"] = "#d5658e"
	textureColorMap["minecraft:pink_concrete_powder"] = "#e499b5"
	textureColorMap["minecraft:pink_coral_block"] = "#cf5b9f"
	textureColorMap["minecraft:pink_glass"] = "#f27fa5"
	textureColorMap["minecraft:pink_glass_pane"] = "#e97a9f"
	textureColorMap["minecraft:pink_glazed_terracotta"] = "#eb9ab5"
	textureColorMap["minecraft:pink_petals"] = "#634857"
	textureColorMap["minecraft:pink_petals_stem"] = "#010101"
	textureColorMap["minecraft:pink_shulker_box"] = "#e6799d"
	textureColorMap["minecraft:pink_terracotta"] = "#a14e4e"
	textureColorMap["minecraft:pink_tulip"] = "#162011"
	textureColorMap["minecraft:pink_wool"] = "#ed8dac"
	textureColorMap["minecraft:piston"] = "#726a5e"
	textureColorMap["minecraft:pitcher_crop"] = "#2b2a20"
	textureColorMap["minecraft:planks"] = "#8c6c4e"
	textureColorMap["minecraft:plenty_pottery_pattern"] = "#683c2f"
	textureColorMap["minecraft:podzol"] = "#6a4b28"
	textureColorMap["minecraft:pointed_dripstone"] = "#1c1613"
	textureColorMap["minecraft:pointed_dripstone_down_base"] = "#745c50"
	textureColorMap["minecraft:pointed_dripstone_down_frustum"] = "#534239"
	textureColorMap["minecraft:pointed_dripstone_down_merge"] = "#2e2520"
	textureColorMap["minecraft:pointed_dripstone_down_middle"] = "#5e4b41"
	textureColorMap["minecraft:pointed_dripstone_up_base"] = "#745c50"
	textureColorMap["minecraft:pointed_dripstone_up_frustum"] = "#534239"
	textureColorMap["minecraft:pointed_dripstone_up_merge"] = "#2e2520"
	textureColorMap["minecraft:pointed_dripstone_up_middle"] = "#5e4b41"
	textureColorMap["minecraft:pointed_dripstone_up_tip"] = "#1c1613"
	textureColorMap["minecraft:polished_andesite"] = "#848685"
	textureColorMap["minecraft:polished_basalt"] = "#5d5d5f"
	textureColorMap["minecraft:polished_blackstone"] = "#353038"
	textureColorMap["minecraft:polished_blackstone_bricks"] = "#302a31"
	textureColorMap["minecraft:polished_deepslate"] = "#484849"
	textureColorMap["minecraft:polished_diorite"] = "#c0c1c2"
	textureColorMap["minecraft:polished_granite"] = "#9a6a59"
	textureColorMap["minecraft:polished_tuff"] = "#616863"
	textureColorMap["minecraft:poppy"] = "#130b05"
	textureColorMap["minecraft:potatoes"] = "#0c1507"
	textureColorMap["minecraft:powder_snow"] = "#f8fdfd"
	textureColorMap["minecraft:powered_rail"] = "#614931"
	textureColorMap["minecraft:prismarine"] = "#639c97"
	textureColorMap["minecraft:prismarine_bricks"] = "#63ab9e"
	textureColorMap["minecraft:prize_pottery_pattern"] = "#6b3e31"
	textureColorMap["minecraft:pumpkin"] = "#bd751d"
	textureColorMap["minecraft:pumpkin_stem_connected"] = "#111111"
	textureColorMap["minecraft:pumpkin_stem_disconnected"] = "#151515"
	textureColorMap["minecraft:purple_candle"] = "#7e7781"
	textureColorMap["minecraft:purple_concrete"] = "#641f9c"
	textureColorMap["minecraft:purple_concrete_powder"] = "#8337b1"
	textureColorMap["minecraft:purple_coral_block"] = "#b720b4"
	textureColorMap["minecraft:purple_glass"] = "#7f3fb2"
	textureColorMap["minecraft:purple_glass_pane"] = "#7a3dab"
	textureColorMap["minecraft:purple_glazed_terracotta"] = "#6d3098"
	textureColorMap["minecraft:purple_shulker_box"] = "#67209c"
	textureColorMap["minecraft:purple_terracotta"] = "#764656"
	textureColorMap["minecraft:purple_wool"] = "#792aac"
	textureColorMap["minecraft:purpur_block"] = "#a97da9"
	textureColorMap["minecraft:purpur_pillar"] = "#ab80ab"
	textureColorMap["minecraft:quartz_block"] = "#ebe5de"
	textureColorMap["minecraft:quartz_bricks"] = "#eae5dd"
	textureColorMap["minecraft:quartz_pillar"] = "#ebe5df"
	textureColorMap["minecraft:rail"] = "#3e372b"
	textureColorMap["minecraft:raw_copper_block"] = "#9a694f"
	textureColorMap["minecraft:raw_gold_block"] = "#dda92e"
	textureColorMap["minecraft:raw_iron_block"] = "#a6876b"
	textureColorMap["minecraft:reactor_core"] = "#5d4853"
	textureColorMap["minecraft:red_candle"] = "#827978"
	textureColorMap["minecraft:red_concrete"] = "#8e2020"
	textureColorMap["minecraft:red_concrete_powder"] = "#a83632"
	textureColorMap["minecraft:red_coral_block"] = "#a22330"
	textureColorMap["minecraft:red_flower"] = "#575d54"
	textureColorMap["minecraft:red_glass"] = "#993333"
	textureColorMap["minecraft:red_glass_pane"] = "#933030"
	textureColorMap["minecraft:red_glazed_terracotta"] = "#b53b35"
	textureColorMap["minecraft:red_mushroom_block"] = "#c82e2d"
	textureColorMap["minecraft:red_nether_brick"] = "#450709"
	textureColorMap["minecraft:red_sand"] = "#be6621"
	textureColorMap["minecraft:red_sandstone"] = "#b8621d"
	textureColorMap["minecraft:red_shulker_box"] = "#8c1f1e"
	textureColorMap["minecraft:red_terracotta"] = "#8f3d2e"
	textureColorMap["minecraft:red_tulip"] = "#131907"
	textureColorMap["minecraft:red_wool"] = "#a02722"
	textureColorMap["minecraft:redstone_block"] = "#af1805"
	textureColorMap["minecraft:redstone_dust_line"] = "#d2d2d2"
	textureColorMap["minecraft:redstone_lamp"] = "#764d2d"
	textureColorMap["minecraft:redstone_ore"] = "#8c6d6d"
	textureColorMap["minecraft:redstone_torch"] = "#0c0603"
	textureColorMap["minecraft:redstone_wire"] = "#b9b9b9"
	textureColorMap["minecraft:reinforced_deepslate"] = "#575b55"
	textureColorMap["minecraft:repeater"] = "#a49d9c"
	textureColorMap["minecraft:repeating_command_block"] = "#806eaa"
	textureColorMap["minecraft:repeating_command_block_conditional"] = "#7f6dab"
	textureColorMap["minecraft:resin_block"] = "#d96319"
	textureColorMap["minecraft:resin_bricks"] = "#cd5818"
	textureColorMap["minecraft:resin_clump"] = "#180c02"
	textureColorMap["minecraft:respawn_anchor"] = "#2f1257"
	textureColorMap["minecraft:respawn_anchor_side0"] = "#27173e"
	textureColorMap["minecraft:respawn_anchor_side1"] = "#2a1a40"
	textureColorMap["minecraft:respawn_anchor_side2"] = "#2c1c41"
	textureColorMap["minecraft:respawn_anchor_side3"] = "#2f1e42"
	textureColorMap["minecraft:respawn_anchor_side4"] = "#312044"
	textureColorMap["minecraft:rooted_dirt"] = "#90674c"
	textureColorMap["minecraft:sand"] = "#dbcfa3"
	textureColorMap["minecraft:sandstone"] = "#dace9f"
	textureColorMap["minecraft:sapling"] = "#282b19"
	textureColorMap["minecraft:scrape_pottery_pattern"] = "#6e4032"
	textureColorMap["minecraft:sculk"] = "#0c1d24"
	textureColorMap["minecraft:sculk_catalyst"] = "#364b4c"
	textureColorMap["minecraft:sculk_sensor"] = "#08262e"
	textureColorMap["minecraft:sculk_sensor_tendril"] = "#010b0c"
	textureColorMap["minecraft:sculk_shrieker"] = "#223130"
	textureColorMap["minecraft:sculk_shrieker_can_summon"] = "#1e4042"
	textureColorMap["minecraft:sculk_vein"] = "#052128"
	textureColorMap["minecraft:sea_lantern"] = "#acc7be"
	textureColorMap["minecraft:sea_pickle"] = "#707645"
	textureColorMap["minecraft:seagrass"] = "#3f632d"
	textureColorMap["minecraft:sheaf_pottery_pattern"] = "#6d3f31"
	textureColorMap["minecraft:shelter_pottery_pattern"] = "#6e3f32"
	textureColorMap["minecraft:short_dry_grass"] = "#231d14"
	textureColorMap["minecraft:shroomlight"] = "#f09246"
	textureColorMap["minecraft:shulker_box"] = "#7a6362"
	textureColorMap["minecraft:silver_concrete"] = "#7d7d73"
	textureColorMap["minecraft:silver_concrete_powder"] = "#9a9a94"
	textureColorMap["minecraft:silver_glass"] = "#999999"
	textureColorMap["minecraft:silver_glass_pane"] = "#939393"
	textureColorMap["minecraft:silver_glazed_terracotta"] = "#90a6a7"
	textureColorMap["minecraft:silver_shulker_box"] = "#7c7c73"
	textureColorMap["minecraft:silver_terracotta"] = "#876a61"
	textureColorMap["minecraft:silver_wool"] = "#8e8e86"
	textureColorMap["minecraft:skull_pottery_pattern"] = "#6c3e31"
	textureColorMap["minecraft:slime_block"] = "#6fc05b"
	textureColorMap["minecraft:small_amethyst_bud"] = "#100c18"
	textureColorMap["minecraft:small_dripleaf"] = "#0c0f05"
	textureColorMap["minecraft:small_dripleaf_stem"] = "#0e1206"
	textureColorMap["minecraft:smithing_table"] = "#3a2729"
	textureColorMap["minecraft:smoker"] = "#635a4c"
	textureColorMap["minecraft:smooth_basalt"] = "#48484e"
	textureColorMap["minecraft:smooth_red_sandstone"] = "#bd651f"
	textureColorMap["minecraft:smooth_sandstone"] = "#d9ce9f"
	textureColorMap["minecraft:sniffer_egg"] = "#40271c"
	textureColorMap["minecraft:sniffer_egg_not_cracked_east"] = "#463624"
	textureColorMap["minecraft:sniffer_egg_not_cracked_north"] = "#50432c"
	textureColorMap["minecraft:sniffer_egg_not_cracked_south"] = "#51442d"
	textureColorMap["minecraft:sniffer_egg_not_cracked_west"] = "#433a26"
	textureColorMap["minecraft:sniffer_egg_slightly_cracked_east"] = "#433323"
	textureColorMap["minecraft:sniffer_egg_slightly_cracked_north"] = "#4e3f2b"
	textureColorMap["minecraft:sniffer_egg_slightly_cracked_south"] = "#4e3f2b"
	textureColorMap["minecraft:sniffer_egg_slightly_cracked_west"] = "#423926"
	textureColorMap["minecraft:sniffer_egg_very_cracked_east"] = "#403022"
	textureColorMap["minecraft:sniffer_egg_very_cracked_north"] = "#4a3b29"
	textureColorMap["minecraft:sniffer_egg_very_cracked_south"] = "#4a3c29"
	textureColorMap["minecraft:sniffer_egg_very_cracked_west"] = "#3e3524"
	textureColorMap["minecraft:snort_pottery_pattern"] = "#693c2f"
	textureColorMap["minecraft:snow"] = "#a99785"
	textureColorMap["minecraft:snow_block"] = "#f9fefe"
	textureColorMap["minecraft:soul_campfire"] = "#366666"
	textureColorMap["minecraft:soul_lantern"] = "#1d292f"
	textureColorMap["minecraft:soul_sand"] = "#513e32"
	textureColorMap["minecraft:soul_soil"] = "#4b392e"
	textureColorMap["minecraft:soul_torch"] = "#080807"
	textureColorMap["minecraft:spawner"] = "#191f2b"
	textureColorMap["minecraft:sponge"] = "#c3c04a"
	textureColorMap["minecraft:spore_blossom"] = "#67304f"
	textureColorMap["minecraft:spore_blossom_base"] = "#46581f"
	textureColorMap["minecraft:spruce_door"] = "#695030"
	textureColorMap["minecraft:spruce_leaves"] = "#676767"
	textureColorMap["minecraft:spruce_log"] = "#533a1f"
	textureColorMap["minecraft:spruce_planks"] = "#725430"
	textureColorMap["minecraft:spruce_sapling"] = "#0e130b"
	textureColorMap["minecraft:spruce_trapdoor"] = "#674f2f"
	textureColorMap["minecraft:stained_glass"] = "#897774"
	textureColorMap["minecraft:stained_hardened_clay"] = "#745446"
	textureColorMap["minecraft:sticky_piston"] = "#7a955c"
	textureColorMap["minecraft:stone"] = "#7d7d7d"
	textureColorMap["minecraft:stone_bricks"] = "#7a797a"
	textureColorMap["minecraft:stone_slab"] = "#918a82"
	textureColorMap["minecraft:stonecutter"] = "#6e6f6f"
	textureColorMap["minecraft:stonecutter2"] = "#645f5a"
	textureColorMap["minecraft:stonecutter_other"] = "#717171"
	textureColorMap["minecraft:stripped_acacia_log"] = "#aa5b37"
	textureColorMap["minecraft:stripped_bamboo_block"] = "#b9a54c"
	textureColorMap["minecraft:stripped_birch_log"] = "#c1ad75"
	textureColorMap["minecraft:stripped_cherry_log"] = "#da9a98"
	textureColorMap["minecraft:stripped_crimson_stem"] = "#813856"
	textureColorMap["minecraft:stripped_dark_oak_log"] = "#44321d"
	textureColorMap["minecraft:stripped_jungle_log"] = "#a87f52"
	textureColorMap["minecraft:stripped_mangrove_log"] = "#72302d"
	textureColorMap["minecraft:stripped_oak_log"] = "#a88851"
	textureColorMap["minecraft:stripped_pale_oak_log"] = "#f0e8e6"
	textureColorMap["minecraft:stripped_spruce_log"] = "#5c4628"
	textureColorMap["minecraft:stripped_warped_stem"] = "#368b87"
	textureColorMap["minecraft:suspicious_gravel"] = "#7e7979"
	textureColorMap["minecraft:suspicious_sand"] = "#d6c798"
	textureColorMap["minecraft:sweet_berry_bush"] = "#1b2a1a"
	textureColorMap["minecraft:tall_dry_grass"] = "#524733"
	textureColorMap["minecraft:tallgrass"] = "#6b5f54"
	textureColorMap["minecraft:target"] = "#e3ada2"
	textureColorMap["minecraft:terracotta"] = "#985e43"
	textureColorMap["minecraft:tinted_glass"] = "#2b262d"
	textureColorMap["minecraft:tnt"] = "#a3483f"
	textureColorMap["minecraft:torch"] = "#0a0804"
	textureColorMap["minecraft:torchflower"] = "#26261d"
	textureColorMap["minecraft:torchflower_crop"] = "#09130d"
	textureColorMap["minecraft:trapdoor"] = "#7b5e3f"
	textureColorMap["minecraft:trapped_chest"] = "#7b5a27"
	textureColorMap["minecraft:trial_spawner"] = "#2b3c49"
	textureColorMap["minecraft:trial_spawner_top_open"] = "#2e333c"
	textureColorMap["minecraft:tuff"] = "#6c6d66"
	textureColorMap["minecraft:tuff_bricks"] = "#62665f"
	textureColorMap["minecraft:turtle_egg"] = "#c2c1ad"
	textureColorMap["minecraft:twisting_vines"] = "#062b26"
	textureColorMap["minecraft:undyed_shulker_box"] = "#8b608b"
	textureColorMap["minecraft:vault"] = "#2f383d"
	textureColorMap["minecraft:verdant_froglight"] = "#dcefda"
	textureColorMap["minecraft:vine"] = "#424242"
	textureColorMap["minecraft:warped_door"] = "#2b7a74"
	textureColorMap["minecraft:warped_fungus"] = "#0e1511"
	textureColorMap["minecraft:warped_nylium"] = "#395750"
	textureColorMap["minecraft:warped_planks"] = "#2b6863"
	textureColorMap["minecraft:warped_roots"] = "#062b27"
	textureColorMap["minecraft:warped_stem"] = "#37535d"
	textureColorMap["minecraft:warped_trapdoor"] = "#255d57"
	textureColorMap["minecraft:warped_wart_block"] = "#167779"
	textureColorMap["minecraft:waterlily"] = "#4e4e4e"
	textureColorMap["minecraft:weathered_chiseled_copper"] = "#68966f"
	textureColorMap["minecraft:weathered_copper"] = "#6c996e"
	textureColorMap["minecraft:weathered_copper_bars"] = "#26372a"
	textureColorMap["minecraft:weathered_copper_bulb"] = "#7c8c62"
	textureColorMap["minecraft:weathered_copper_chain1"] = "#080c0a"
	textureColorMap["minecraft:weathered_copper_chain2"] = "#070b09"
	textureColorMap["minecraft:weathered_copper_chest_inventory"] = "#69946b"
	textureColorMap["minecraft:weathered_copper_door"] = "#62845f"
	textureColorMap["minecraft:weathered_copper_grate"] = "#4a6a4d"
	textureColorMap["minecraft:weathered_copper_lantern"] = "#273729"
	textureColorMap["minecraft:weathered_copper_trapdoor"] = "#567a57"
	textureColorMap["minecraft:weathered_cut_copper"] = "#6d916b"
	textureColorMap["minecraft:weathered_lightning_rod"] = "#ced5cf"
	textureColorMap["minecraft:web"] = "#5d5f60"
	textureColorMap["minecraft:weeping_vines"] = "#0a0002"
	textureColorMap["minecraft:weeping_vines_base"] = "#3b0812"
	textureColorMap["minecraft:weeping_vines_plant"] = "#3b0705"
	textureColorMap["minecraft:wet_sponge"] = "#abb546"
	textureColorMap["minecraft:wheat"] = "#182509"
	textureColorMap["minecraft:white_candle"] = "#868685"
	textureColorMap["minecraft:white_concrete"] = "#cfd5d6"
	textureColorMap["minecraft:white_concrete_powder"] = "#e1e3e3"
	textureColorMap["minecraft:white_glass"] = "#ffffff"
	textureColorMap["minecraft:white_glass_pane"] = "#f6f6f6"
	textureColorMap["minecraft:white_glazed_terracotta"] = "#bcd4ca"
	textureColorMap["minecraft:white_shulker_box"] = "#d7dcdd"
	textureColorMap["minecraft:white_terracotta"] = "#d1b2a1"
	textureColorMap["minecraft:white_tulip"] = "#131f0f"
	textureColorMap["minecraft:white_wool"] = "#e9ecec"
	textureColorMap["minecraft:wildflowers"] = "#38321b"
	textureColorMap["minecraft:wildflowers_stem"] = "#010101"
	textureColorMap["minecraft:wither_rose"] = "#060803"
	textureColorMap["minecraft:wood"] = "#856f4d"
	textureColorMap["minecraft:wood_door"] = "#7e6339"
	textureColorMap["minecraft:wooden_door"] = "#846546"
	textureColorMap["minecraft:wooden_slab"] = "#9c8152"
	textureColorMap["minecraft:wool"] = "#826e67"
	textureColorMap["minecraft:yellow_candle"] = "#86837a"
	textureColorMap["minecraft:yellow_concrete"] = "#f0af15"
	textureColorMap["minecraft:yellow_concrete_powder"] = "#e8c736"
	textureColorMap["minecraft:yellow_coral_block"] = "#d8c742"
	textureColorMap["minecraft:yellow_glass"] = "#e5e533"
	textureColorMap["minecraft:yellow_glass_pane"] = "#dddd30"
	textureColorMap["minecraft:yellow_glazed_terracotta"] = "#eac058"
	textureColorMap["minecraft:yellow_shulker_box"] = "#f8bc1d"
	textureColorMap["minecraft:yellow_terracotta"] = "#ba8523"
	textureColorMap["minecraft:yellow_wool"] = "#f8c527"
}